export type RepoDetail = {
  full_name: string;
  name: string;
  owner: string;
  html_url: string;
  description?: string | null;
  language?: string | null;
  stargazers_count?: number | null;
  forks_count?: number | null;
  topics: string[];
  star_users?: string[];
  category?: string | null;
  subcategory?: string | null;
  tags?: string[];
  tag_ids?: string[];
  ai_category?: string | null;
  ai_subcategory?: string | null;
  ai_confidence?: number | null;
  ai_tags?: string[];
  ai_tag_ids?: string[];
  ai_reason?: string | null;
  ai_decision_source?: string | null;
  ai_rule_candidates?: Array<{
    rule_id?: string;
    score?: number;
    category?: string;
    subcategory?: string;
    evidence?: string[];
    tag_ids?: string[];
  }>;
  ai_provider?: string | null;
  ai_model?: string | null;
  ai_updated_at?: string | null;
  override_category?: string | null;
  override_subcategory?: string | null;
  override_tags?: string[];
  override_tag_ids?: string[];
  override_note?: string | null;
  readme_summary?: string | null;
  readme_fetched_at?: string | null;
  pushed_at?: string | null;
  updated_at?: string | null;
  starred_at?: string | null;
};

export type OverrideHistoryItem = {
  category?: string | null;
  subcategory?: string | null;
  tags?: string[];
  note?: string | null;
  updated_at?: string | null;
};
